# Generated by Django 5.2.17 on 2026-09-04 19:38

from datetime import timedelta

from django.db import migrations, models

import accounts.models.password_reset_token
from games.settings import Settings


def _backfill_expires_at(apps, schema_editor):
    """Set `expires_at` for every pre-existing token, based on its own `created_at`.

    Uses `created_at + configured expiration minutes` rather than the field's `default=`
    (which is `now() + configured minutes`), so already-expired tokens stay expired instead
    of being silently extended by this migration.
    """
    PasswordResetToken = apps.get_model("accounts", "PasswordResetToken")
    expiration = timedelta(minutes=Settings.password_reset_token_expiration_minutes())

    for token in PasswordResetToken.objects.all():
        token.expires_at = token.created_at + expiration
        token.save(update_fields=["expires_at"])


def _noop_reverse(apps, schema_editor):
    """No-op reverse migration — `expires_at` removal is handled by its own AddField reversal."""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_passwordresettoken_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_expires_at, _noop_reverse),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=accounts.models.password_reset_token._default_expires_at,
            ),
        ),
    ]
