# Generated by Django 5.2.17 on 2026-08-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('domain_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='domains.domaingroup')),
            ],
        ),
    ]
