# Generated by Django 5.2.17 on 2026-08-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_migrate_domain_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='title',
        ),
    ]
