engines:
  duplication:
    exclude_paths:
      - "frontend/specs/**"
      - "source/games/tests/**"
  bandit:
    exclude_paths:
      - "source/games/tests/**"
  phpmd:
    exclude_paths:
      - "proxy/extension/tests/**"
  phpcs:
    exclude_paths:
      - "proxy/extension/tests/**"
