"""Views for game-scoped nested resources (PCs, NPCs)."""

from .npcs import (
    game_npc_access,
    game_npc_detail,
    game_npc_full,
    game_npc_money,
    game_npc_permissions,
    game_npc_photo_set,
    game_npc_photo_upload,
    game_npc_photos,
    game_npc_treasure_acquire,
    game_npc_treasure_acquire_all,
    game_npc_treasure_sell,
    game_npc_treasures,
    game_npc_treasures_all,
    game_npcs,
    game_npcs_all,
)
from .pcs import (
    game_pc_access,
    game_pc_detail,
    game_pc_full,
    game_pc_money,
    game_pc_permissions,
    game_pc_photo_set,
    game_pc_photo_upload,
    game_pc_photos,
    game_pc_treasure_acquire,
    game_pc_treasure_acquire_all,
    game_pc_treasure_sell,
    game_pc_treasures,
    game_pcs,
)

__all__ = [
    'game_pcs',
    'game_npcs',
    'game_npc_detail',
    'game_npcs_all',
    'game_pc_detail',
    'game_npc_full',
    'game_pc_full',
    'game_pc_money',
    'game_npc_money',
    'game_pc_access',
    'game_npc_access',
    'game_pc_permissions',
    'game_npc_permissions',
    'game_pc_photo_upload',
    'game_npc_photo_upload',
    'game_pc_photo_set',
    'game_npc_photo_set',
    'game_pc_photos',
    'game_npc_photos',
    'game_pc_treasures',
    'game_npc_treasures',
    'game_npc_treasures_all',
    'game_pc_treasure_acquire',
    'game_pc_treasure_acquire_all',
    'game_pc_treasure_sell',
    'game_npc_treasure_acquire',
    'game_npc_treasure_acquire_all',
    'game_npc_treasure_sell',
]
