# Generated by Django 5.2.15 on 2026-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_treasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='treasures',
            field=models.ManyToManyField(blank=True, to='games.treasure'),
        ),
    ]
