# Generated by Django 5.2.15 on 2026-06-29 16:35

from django.db import migrations, models


def copy_character_class_to_role(apps, schema_editor):
    """Copy character_class value into role for every character where role is null."""
    Character = apps.get_model("games", "Character")
    for character in Character.objects.filter(role__isnull=True).exclude(character_class=""):
        if character.character_class:
            character.role = character.character_class
            character.save(update_fields=["role"])


class Migration(migrations.Migration):
    """Migration to replace character_class and level fields with a single role field."""

    dependencies = [
        ("games", "0024_game_treasures"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="role",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(copy_character_class_to_role, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="character",
            name="character_class",
        ),
        migrations.RemoveField(
            model_name="character",
            name="level",
        ),
    ]
