# Generated by Django 5.2.15 on 2026-07-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_remove_gamephoto_url_game_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('ready', models.BooleanField(default=False)),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='games.character',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='profile_photo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='games.characterphoto',
            ),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
