# Generated by Django 5.2.15 on 2026-07-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_characterphoto_character_profile_photo_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='photo',
        ),
    ]
