# Generated by Django 5.2.15 on 2026-07-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_charactertreasure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charactertreasure',
            unique_together={('character', 'treasure')},
        ),
    ]
