# Generated by Django 5.2.15 on 2026-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_character_allegiance_character_public_allegiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlink',
            name='link_type',
            field=models.CharField(
                blank=True, choices=[('lootstudio', 'LootStudio')], default='', max_length=32
            ),
        ),
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.CharField(
                blank=True, choices=[('lootstudio', 'LootStudio')], default='', max_length=32
            ),
        ),
    ]
