# Generated by Django 5.2.15 on 2026-07-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_character_public_slain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('single', 'Single'), ('multiple', 'Multiple')],
                        default='single',
                        max_length=16,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'), ('inactive', 'Inactive'), ('closed', 'Closed'),
                        ],
                        default='inactive',
                        max_length=16,
                    ),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='polls',
                        to='games.game',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('option', models.CharField(max_length=200)),
                (
                    'poll',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='options',
                        to='games.poll',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'option',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='games.polloption',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='poll_votes',
                        to='games.player',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('player', 'option')},
            },
        ),
    ]
