# Generated by Django 5.2.15 on 2026-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
