# Generated by Django 5.2.15 on 2026-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_gamesession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(
                choices=[
                    ('dnd', 'D&D'),
                    ('deadlands', 'Deadlands'),
                ],
                default='dnd',
                max_length=16,
            ),
        ),
    ]
