# Generated by Django 5.2.15 on 2026-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0047_gamesessionmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessionmessage',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
