# Generated by Django 5.2.15 on 2026-07-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_alter_gamesessionmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
