# Generated by Django 5.2.15 on 2026-07-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_poll_description_poll_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
