# Generated by Django 5.2.15 on 2026-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_alter_poll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_type',
            field=models.CharField(
                choices=[('text', 'Text'), ('date', 'Date')], default='text', max_length=16,
            ),
        ),
    ]
