# Generated by Django 5.2.15 on 2026-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0053_pollvote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
