# Generated by Django 5.2.15 on 2026-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_charactertreasure_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametreasure',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
