# Generated by Django 5.2.15 on 2026-07-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_backfill_gametreasure_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='hidden',
        ),
    ]
