# Generated by Django 5.2.15 on 2026-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add UserProfile.display_name, nullable/unique, backfilled separately."""

    dependencies = [
        ('games', '0060_remove_treasure_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
