# Generated by Django 5.2.15 on 2026-07-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_alter_characterlink_link_type_alter_link_link_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameMaster',
        ),
    ]
