# Generated by Django 5.2.15 on 2026-07-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0068_delete_gamemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_items',
                        to='games.character',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterItemPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('ready', models.BooleanField(default=False)),
                (
                    'character_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='games.characteritem',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='characteritem',
            name='photo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='games.characteritemphoto',
            ),
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('hidden', models.BooleanField(default=False)),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='games.game',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='characteritem',
            name='game_item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='character_items',
                to='games.gameitem',
            ),
        ),
        migrations.CreateModel(
            name='GameItemPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('ready', models.BooleanField(default=False)),
                (
                    'game_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='games.gameitem',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='gameitem',
            name='photo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='games.gameitemphoto',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='characteritem',
            unique_together={('character', 'game_item')},
        ),
    ]
