# Generated by Django 5.2.15 on 2026-07-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0069_characteritem_characteritemphoto_characteritem_photo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('player',), name='unique_player_character'),
        ),
    ]
