# Generated by Django 5.2.15 on 2026-07-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0073_rename_slain_and_allegiance_to_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='upload_type',
            field=models.CharField(
                choices=[('image', 'image'), ('file', 'file')],
                default='image',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='GameDocumentFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('ready', models.BooleanField(default=False)),
                (
                    'game_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='games.gamedocument',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
