# Generated by Django 5.2.15 on 2026-07-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0074_upload_upload_type_gamedocumentfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameDocumentFilePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("ready", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gamedocumentfile",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="gamedocumentfile",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="games.gamedocumentfilephoto",
            ),
        ),
    ]
