# Generated by Django 5.2.15 on 2026-07-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0078_character_incognito'),
        ('versioning', '0016_remove_historicalcharacterdocument_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterdocument',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='characterdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='characterdocument',
            name='name',
        ),
        migrations.DeleteModel(
            name='CharacterDocumentPhoto',
        ),
    ]
