# Generated by Django 5.2.15 on 2026-07-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0079_remove_characterdocument_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='profile_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='cover_photo',
            new_name='photo',
        ),
    ]
