# Generated by Django 5.2.15 on 2026-08-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0080_rename_profile_photo_character_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterlink',
            name='link_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('lootstudio', 'LootStudio'),
                    ('youtube', 'YouTube'),
                    ('diary', 'Diary'),
                    ('music', 'Music'),
                    ('stl', 'STL'),
                    ('background', 'Background'),
                    ('reference', 'Reference'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='gamelink',
            name='link_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('lootstudio', 'LootStudio'),
                    ('youtube', 'YouTube'),
                    ('diary', 'Diary'),
                    ('music', 'Music'),
                    ('stl', 'STL'),
                    ('background', 'Background'),
                    ('reference', 'Reference'),
                ],
                default='',
                max_length=32,
            ),
        ),
    ]
