# Generated by Django 5.2.15 on 2026-08-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0081_alter_characterlink_link_type_alter_gamelink_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDomainGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameDomain',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('domain', models.CharField(max_length=200, unique=True)),
                (
                    'game_domain_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domains',
                        to='games.gamedomaingroup',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_domain_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='games',
                to='games.gamedomaingroup',
            ),
        ),
    ]
