# Generated by Django 5.2.15 on 2026-08-04 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0084_alter_gamedomain_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedomain',
            name='domain',
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message='domain must be a valid hostname (labels of letters, digits'
                        ' and hyphens separated by dots, no wildcards or whitespace).',
                        regex=(
                            '\\A([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)'
                            '(\\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+\\Z'
                        ),
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name='gamedomain',
            constraint=models.UniqueConstraint(
                fields=('domain', 'game_domain_group'), name='unique_domain_per_group'
            ),
        ),
    ]
