# Generated by Django 5.2.15 on 2026-08-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0088_remove_game_game_domain_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteritem',
            unique_together=set(),
        ),
    ]
