# Generated by Django 5.2.15 on 2026-08-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0092_gamepossession_gamepossessionphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='factions',
                        to='games.game',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='factions',
            field=models.ManyToManyField(
                blank=True, related_name='characters', to='games.faction',
            ),
        ),
        migrations.CreateModel(
            name='FactionPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('ready', models.BooleanField(default=False)),
                (
                    'faction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='games.faction',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='photo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='games.factionphoto',
            ),
        ),
        migrations.AddConstraint(
            model_name='faction',
            constraint=models.UniqueConstraint(
                fields=('game', 'name'), name='unique_faction_name_per_game',
            ),
        ),
    ]
