# Generated by Django 5.2.15 on 2026-08-12 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0093_faction_character_factions_factionphoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterPossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_possessions",
                        to="games.character",
                    ),
                ),
                (
                    "game_possession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_possessions",
                        to="games.gamepossession",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("character", "game_possession")},
            },
        ),
    ]
