# Generated by Django 5.2.15 on 2026-08-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0094_characterpossession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faction',
            new_name='GameFaction',
        ),
        migrations.RenameModel(
            old_name='FactionPhoto',
            new_name='GameFactionPhoto',
        ),
        migrations.RemoveField(
            model_name='character',
            name='factions',
        ),
    ]
