# Generated by Django 5.2.15 on 2026-08-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0095_rename_faction_gamefaction_and_more'),
        ('versioning', '0032_rename_historicalfaction_historicalgamefaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('hidden', models.BooleanField(default=False)),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_factions',
                        to='games.character',
                    ),
                ),
                (
                    'game_faction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_factions',
                        to='games.gamefaction',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('character', 'game_faction')},
            },
        ),
    ]
