# Generated by Django 5.2.15 on 2026-08-14 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0096_characterfaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterlink",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])]
            ),
        ),
        migrations.AlterField(
            model_name="gamelink",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])]
            ),
        ),
    ]
