# Generated by Django 5.2.15 on 2026-08-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0097_alter_characterlink_url_alter_gamelink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDocumentPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField()),
                (
                    'game_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pages',
                        to='games.gamedocument',
                    ),
                ),
            ],
            options={
                'ordering': ['game_document', 'order'],
            },
        ),
    ]
