# Generated by Django 5.2.15 on 2026-08-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0098_gamedocumentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedocumentpage',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
