# Generated by Django 5.2.15 on 2026-08-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0099_gamedocumentpage_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDocumentPageHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('order', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, default='')),
                (
                    'game_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='page_history',
                        to='games.gamedocument',
                    ),
                ),
            ],
            options={
                'ordering': ['game_document', 'version', 'order'],
            },
        ),
    ]
