# Generated by Django 5.2.15 on 2026-08-18 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0100_gamedocumentpagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCommonItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('hidden', models.BooleanField(default=False)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('potion', 'Potion'),
                            ('drug', 'Drug'),
                            ('consumable', 'Consumable'),
                            ('ammunition', 'Ammunition'),
                            ('poison', 'Poison'),
                            ('gear', 'Gear'),
                            ('other', 'Other'),
                        ],
                        default='other',
                        max_length=16,
                    ),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='common_items',
                        to='games.game',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GameCommonItemPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('ready', models.BooleanField(default=False)),
                (
                    'game_common_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='games.gamecommonitem',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gamecommonitem',
            name='photo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='games.gamecommonitemphoto',
            ),
        ),
    ]
