# Generated by Django 5.2.17 on 2026-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0101_gamecommonitem_gamecommonitemphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(
                choices=[
                    ('printing', 'Printing'),
                    ('crafting', 'Crafting'),
                    ('painting', 'Painting'),
                    ('planning', 'Planning'),
                    ('writing', 'Writing'),
                    ('research', 'Research'),
                    ('scheduling', 'Scheduling'),
                    ('buying', 'Buying'),
                    ('updating', 'Updating'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=16,
            ),
        ),
    ]
