# Generated by Django 5.2.17 on 2026-09-29 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0102_task_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('hidden', models.BooleanField(default=False)),
                (
                    'yield_quantity',
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('crafting_time', models.CharField(blank=True, default='', max_length=200)),
                (
                    'crafting_cost',
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('ingredients', models.TextField(blank=True, default='')),
                ('checks', models.TextField(blank=True, default='')),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recipes',
                        to='games.game',
                    ),
                ),
                (
                    'game_common_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recipes',
                        to='games.gamecommonitem',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
