# Generated by Django 5.2.17 on 2026-09-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0103_gamerecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRecipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('hidden', models.BooleanField(default=False)),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_recipes',
                        to='games.character',
                    ),
                ),
                (
                    'game_recipe',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_recipes',
                        to='games.gamerecipe',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('character', 'game_recipe')},
            },
        ),
    ]
