"""URL patterns for games' own actions and sub-resources not yet restructured."""

from django.urls import path

from ..views.game import (
    game_npc_document_summary,
    game_npc_document_summary_all,
    game_npc_faction_summary,
    game_npc_faction_summary_all,
    game_npc_item_summary,
    game_npc_item_summary_all,
    game_npc_treasure_summary,
    game_npc_treasure_summary_all,
    game_pc_document_summary,
    game_pc_document_summary_all,
    game_pc_faction_summary,
    game_pc_faction_summary_all,
    game_pc_item_summary,
    game_pc_item_summary_all,
    game_pc_treasure_summary,
    game_pc_treasure_summary_all,
)
from ..views.game_sessions import (
    game_session_detail,
    game_sessions_create,
    game_sessions_future,
    game_sessions_past,
    game_sessions_unscheduled,
    session_messages_list,
    session_poll_create,
)
from ..views.game_tasks import game_task_detail, game_tasks_list
from ..views.games import (
    game_access,
    game_common_item_detail,
    game_common_item_detail_full,
    game_common_item_photo_upload,
    game_common_items,
    game_common_items_all,
    game_detail,
    game_document_detail,
    game_document_detail_full,
    game_document_file_photo_upload,
    game_document_file_upload,
    game_document_files,
    game_document_files_all,
    game_document_page_detail,
    game_document_page_detail_all,
    game_document_pages,
    game_document_pages_all,
    game_document_pages_bump_version,
    game_document_pages_bump_version_all,
    game_document_photo_set,
    game_document_photo_upload,
    game_document_photos,
    game_document_photos_all,
    game_documents,
    game_documents_all,
    game_faction_characters,
    game_faction_characters_all,
    game_faction_detail,
    game_faction_photo_upload,
    game_factions,
    game_item_detail,
    game_item_detail_full,
    game_item_photo_upload,
    game_items,
    game_items_all,
    game_photos,
    game_possession_detail,
    game_possession_detail_full,
    game_possession_photo_upload,
    game_possessions,
    game_possessions_all,
    game_treasure_detail,
    game_treasure_link,
    game_treasures,
    game_treasures_all,
    game_treasures_missing,
    games_list,
    my_games_list,
)
from ..views.photo_upload import photo_upload
from ..views.polls import game_poll_close, game_poll_detail, game_poll_votes, game_polls_list

urlpatterns = [
    path('games.json', games_list, name='games-list'),
    path('my-games.json', my_games_list, name='my-games-list'),
    path('games/<slug:game_slug>.json', game_detail, name='game-detail'),
    path('games/<slug:game_slug>/access.json', game_access, name='game-access'),
    path('games/<slug:game_slug>/treasures.json', game_treasures, name='game-treasures'),
    path(
        'games/<slug:game_slug>/treasures/all.json',
        game_treasures_all,
        name='game-treasures-all',
    ),
    path(
        'games/<slug:game_slug>/treasures/missing.json',
        game_treasures_missing,
        name='game-treasures-missing',
    ),
    path(
        'games/<slug:game_slug>/treasures/link.json',
        game_treasure_link,
        name='game-treasure-link',
    ),
    path(
        'games/<slug:game_slug>/treasures/<int:treasure_id>.json',
        game_treasure_detail,
        name='game-treasure-detail',
    ),
    path(
        'games/<slug:game_slug>/treasures/<int:treasure_id>/pcs/<int:character_id>/summary.json',
        game_pc_treasure_summary,
        name='game-treasure-pc-summary',
    ),
    path(
        (
            'games/<slug:game_slug>/treasures/<int:treasure_id>/pcs/<int:character_id>/'
            'summary/all.json'
        ),
        game_pc_treasure_summary_all,
        name='game-treasure-pc-summary-all',
    ),
    path(
        'games/<slug:game_slug>/treasures/<int:treasure_id>/npcs/<int:character_id>/summary.json',
        game_npc_treasure_summary,
        name='game-treasure-npc-summary',
    ),
    path(
        (
            'games/<slug:game_slug>/treasures/<int:treasure_id>/npcs/<int:character_id>/'
            'summary/all.json'
        ),
        game_npc_treasure_summary_all,
        name='game-treasure-npc-summary-all',
    ),
    path(
        'games/<slug:game_slug>/documents.json', game_documents, name='game-documents',
    ),
    path(
        'games/<slug:game_slug>/documents/all.json',
        game_documents_all,
        name='game-documents-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>.json',
        game_document_detail,
        name='game-document-detail',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/full.json',
        game_document_detail_full,
        name='game-document-detail-full',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/photos.json',
        game_document_photos,
        name='game-document-photos',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/photos/all.json',
        game_document_photos_all,
        name='game-document-photos-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/files.json',
        game_document_files,
        name='game-document-files',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/files/all.json',
        game_document_files_all,
        name='game-document-files-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pages.json',
        game_document_pages,
        name='game-document-pages',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pages/all.json',
        game_document_pages_all,
        name='game-document-pages-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pages/bump_version.json',
        game_document_pages_bump_version,
        name='game-document-pages-bump-version',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pages/bump_version/all.json',
        game_document_pages_bump_version_all,
        name='game-document-pages-bump-version-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pages/<int:page_id>.json',
        game_document_page_detail,
        name='game-document-page-detail',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pages/<int:page_id>/all.json',
        game_document_page_detail_all,
        name='game-document-page-detail-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/photo_upload.json',
        game_document_photo_upload,
        name='game-document-photo-upload',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/file_upload.json',
        game_document_file_upload,
        name='game-document-file-upload',
    ),
    path(
        (
            'games/<slug:game_slug>/documents/<int:document_id>/files/<int:file_id>/'
            'photo_upload.json'
        ),
        game_document_file_photo_upload,
        name='game-document-file-photo-upload',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/photos/<int:photo_id>/set.json',
        game_document_photo_set,
        name='game-document-photo-set',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/pcs/<int:character_id>/summary.json',
        game_pc_document_summary,
        name='game-document-pc-summary',
    ),
    path(
        (
            'games/<slug:game_slug>/documents/<int:document_id>/pcs/<int:character_id>/'
            'summary/all.json'
        ),
        game_pc_document_summary_all,
        name='game-document-pc-summary-all',
    ),
    path(
        'games/<slug:game_slug>/documents/<int:document_id>/npcs/<int:character_id>/summary.json',
        game_npc_document_summary,
        name='game-document-npc-summary',
    ),
    path(
        (
            'games/<slug:game_slug>/documents/<int:document_id>/npcs/<int:character_id>/'
            'summary/all.json'
        ),
        game_npc_document_summary_all,
        name='game-document-npc-summary-all',
    ),
    path('games/<slug:game_slug>/factions.json', game_factions, name='game-factions'),
    path(
        'games/<slug:game_slug>/factions/<int:faction_id>.json',
        game_faction_detail,
        name='game-faction-detail',
    ),
    path(
        'games/<slug:game_slug>/factions/<int:faction_id>/photo_upload.json',
        game_faction_photo_upload,
        name='game-faction-photo-upload',
    ),
    path(
        'games/<slug:game_slug>/factions/<int:faction_id>/characters.json',
        game_faction_characters,
        name='game-faction-characters',
    ),
    path(
        'games/<slug:game_slug>/factions/<int:faction_id>/characters/all.json',
        game_faction_characters_all,
        name='game-faction-characters-all',
    ),
    path(
        'games/<slug:game_slug>/factions/<int:faction_id>/pcs/<int:character_id>/summary.json',
        game_pc_faction_summary,
        name='game-faction-pc-summary',
    ),
    path(
        (
            'games/<slug:game_slug>/factions/<int:faction_id>/pcs/<int:character_id>/'
            'summary/all.json'
        ),
        game_pc_faction_summary_all,
        name='game-faction-pc-summary-all',
    ),
    path(
        'games/<slug:game_slug>/factions/<int:faction_id>/npcs/<int:character_id>/summary.json',
        game_npc_faction_summary,
        name='game-faction-npc-summary',
    ),
    path(
        (
            'games/<slug:game_slug>/factions/<int:faction_id>/npcs/<int:character_id>/'
            'summary/all.json'
        ),
        game_npc_faction_summary_all,
        name='game-faction-npc-summary-all',
    ),
    path('games/<slug:game_slug>/items.json', game_items, name='game-items'),
    path(
        'games/<slug:game_slug>/items/all.json',
        game_items_all,
        name='game-items-all',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>.json',
        game_item_detail,
        name='game-item-detail',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>/full.json',
        game_item_detail_full,
        name='game-item-detail-full',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>/photo_upload.json',
        game_item_photo_upload,
        name='game-item-photo-upload',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>/pcs/<int:character_id>/summary.json',
        game_pc_item_summary,
        name='game-item-pc-summary',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>/pcs/<int:character_id>/summary/all.json',
        game_pc_item_summary_all,
        name='game-item-pc-summary-all',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>/npcs/<int:character_id>/summary.json',
        game_npc_item_summary,
        name='game-item-npc-summary',
    ),
    path(
        'games/<slug:game_slug>/items/<int:item_id>/npcs/<int:character_id>/summary/all.json',
        game_npc_item_summary_all,
        name='game-item-npc-summary-all',
    ),
    path(
        'games/<slug:game_slug>/possessions.json',
        game_possessions,
        name='game-possessions',
    ),
    path(
        'games/<slug:game_slug>/possessions/all.json',
        game_possessions_all,
        name='game-possessions-all',
    ),
    path(
        'games/<slug:game_slug>/possessions/<int:possession_id>.json',
        game_possession_detail,
        name='game-possession-detail',
    ),
    path(
        'games/<slug:game_slug>/possessions/<int:possession_id>/full.json',
        game_possession_detail_full,
        name='game-possession-detail-full',
    ),
    path(
        'games/<slug:game_slug>/possessions/<int:possession_id>/photo_upload.json',
        game_possession_photo_upload,
        name='game-possession-photo-upload',
    ),
    path(
        'games/<slug:game_slug>/common_items.json',
        game_common_items,
        name='game-common-items',
    ),
    path(
        'games/<slug:game_slug>/common_items/all.json',
        game_common_items_all,
        name='game-common-items-all',
    ),
    path(
        'games/<slug:game_slug>/common_items/<int:common_item_id>.json',
        game_common_item_detail,
        name='game-common-item-detail',
    ),
    path(
        'games/<slug:game_slug>/common_items/<int:common_item_id>/full.json',
        game_common_item_detail_full,
        name='game-common-item-detail-full',
    ),
    path(
        'games/<slug:game_slug>/common_items/<int:common_item_id>/photo_upload.json',
        game_common_item_photo_upload,
        name='game-common-item-photo-upload',
    ),
    path('games/<slug:game_slug>/photos.json', game_photos, name='game-photos'),
    path(
        'games/<slug:game_slug>/sessions.json',
        game_sessions_create,
        name='game-sessions-list',
    ),
    path(
        'games/<slug:game_slug>/sessions/past.json',
        game_sessions_past,
        name='game-sessions-past',
    ),
    path(
        'games/<slug:game_slug>/sessions/future.json',
        game_sessions_future,
        name='game-sessions-future',
    ),
    path(
        'games/<slug:game_slug>/sessions/unscheduled.json',
        game_sessions_unscheduled,
        name='game-sessions-unscheduled',
    ),
    path(
        'games/<slug:game_slug>/sessions/<int:session_id>.json',
        game_session_detail,
        name='game-session-detail',
    ),
    path(
        'games/<slug:game_slug>/sessions/<int:session_id>/messages.json',
        session_messages_list,
        name='session-messages-list',
    ),
    path(
        'games/<slug:game_slug>/sessions/<int:session_id>/poll.json',
        session_poll_create,
        name='game-session-poll-create',
    ),
    path('games/<slug:game_slug>/tasks.json', game_tasks_list, name='game-tasks-list'),
    path(
        'games/<slug:game_slug>/tasks/<int:task_id>.json',
        game_task_detail,
        name='game-task-detail',
    ),
    path('games/<slug:game_slug>/polls.json', game_polls_list, name='game-polls-list'),
    path(
        'games/<slug:game_slug>/polls/<int:poll_id>.json',
        game_poll_detail,
        name='game-poll-detail',
    ),
    path(
        'games/<slug:game_slug>/polls/<int:poll_id>/votes.json',
        game_poll_votes,
        name='game-poll-votes',
    ),
    path(
        'games/<slug:game_slug>/polls/<int:poll_id>/close.json',
        game_poll_close,
        name='game-poll-close',
    ),
    path(
        'games/<slug:game_slug>/photo_upload.json',
        photo_upload,
        name='game-photo-upload',
    ),
]
