# Generated by Django 5.2.15 on 2026-06-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    """Align model Meta ordering options with the existing model definitions."""

    dependencies = [
        ('games', '0009_character_class_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
    ]
