# Generated by Django 5.2.15 on 2026-06-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamephoto',
            name='path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='gamephoto',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamephoto',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
