# Generated by Django 5.2.15 on 2026-06-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('games', '0018_gamephoto_path_gamephoto_ready_alter_gamephoto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AddField(
            model_name='upload',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
