# Generated by Django 5.2.15 on 2026-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_upload_content_type_upload_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
