# Generated by Django 5.2.15 on 2026-06-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_link_polymorphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
