# Generated by Django 5.2.15 on 2026-07-02 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_remove_character_character_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamephoto',
            name='url',
        ),
        migrations.AddField(
            model_name='game',
            name='cover_photo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='games.gamephoto',
            ),
        ),
    ]
