# Generated by Django 5.2.15 on 2026-07-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_remove_character_avatar_url_remove_game_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
