# Generated by Django 5.2.15 on 2026-07-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_treasurephoto_treasure_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to='games.game',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
