# Generated by Django 5.2.15 on 2026-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slain',
            field=models.BooleanField(default=False),
        ),
    ]
