# Generated by Django 5.2.15 on 2026-07-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_character_slain'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='game',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exclusive_treasures',
                to='games.game',
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='treasures',
            field=models.ManyToManyField(
                blank=True,
                related_name='linked_games',
                related_query_name='linked_game',
                to='games.treasure',
            ),
        ),
    ]
