# Generated by Django 5.2.15 on 2026-07-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_treasure_game_alter_game_treasures'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTreasure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('quantity', models.PositiveIntegerField(default=0)),
                (
                    'character',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_treasures',
                        to='games.character',
                    ),
                ),
                (
                    'treasure',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='character_treasures',
                        to='games.treasure',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
