# Generated by Django 5.2.15 on 2026-07-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_alter_charactertreasure_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
