# Generated by Django 5.2.15 on 2026-07-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_treasure_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTreasure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('max_units', models.PositiveIntegerField(blank=True, null=True)),
                ('acquired_units', models.PositiveIntegerField(default=0)),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='game_treasures', to='games.game',
                    ),
                ),
                (
                    'treasure',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='game_treasures', to='games.treasure',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('game', 'treasure')},
            },
        ),
        # AlterField cannot add/remove `through=` on an M2M field (Django's schema editor
        # rejects it outright), so the field is dropped and re-added instead.
        migrations.RemoveField(
            model_name='game',
            name='treasures',
        ),
        migrations.AddField(
            model_name='game',
            name='treasures',
            field=models.ManyToManyField(
                blank=True, related_name='linked_games', related_query_name='linked_game',
                through='games.GameTreasure', to='games.treasure',
            ),
        ),
    ]
