# Generated by Django 5.2.15 on 2026-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_gametreasure_alter_game_treasures'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='allegiance',
            field=models.CharField(
                choices=[
                    ('ally', 'Ally'),
                    ('enemy', 'Enemy'),
                    ('neutral', 'Neutral'),
                ],
                default='neutral',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='public_allegiance',
            field=models.CharField(
                choices=[
                    ('ally', 'Ally'),
                    ('enemy', 'Enemy'),
                    ('neutral', 'Neutral'),
                ],
                default='neutral',
                max_length=16,
            ),
        ),
    ]
