# Generated by Django 5.2.15 on 2026-07-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_characterlink_link_type_link_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('short_description', models.CharField(max_length=200)),
                ('long_description', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to='games.game',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tasks',
                        to='games.gamesession',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
