# Generated by Django 5.2.15 on 2026-07-09 00:00

from django.db import migrations, models


def _backfill_public_slain(apps, schema_editor):
    """Set public_slain equal to slain for every existing Character row."""
    Character = apps.get_model('games', 'Character')
    Character.objects.update(public_slain=models.F('slain'))


def _noop_reverse(apps, schema_editor):
    """No-op reverse migration — public_slain removal is handled by RemoveField."""


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='public_slain',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_backfill_public_slain, _noop_reverse),
    ]
