version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - pytest:
          filters: &all_tags
            tags:
              only: /.*/
          requires: [release-circleci_majora-base, release-circleci_majora-base-arm64]
      - jasmine:
          filters: *all_tags
          requires: [release-vite_majora-base, release-vite_majora-base-arm64]
      - checks:
          filters: *all_tags
          requires: [release-circleci_majora-base, release-circleci_majora-base-arm64]
      - frontend-checks:
          filters: *all_tags
          requires: [release-vite_majora-base, release-vite_majora-base-arm64]
      - coverage-final:
          requires: [pytest, jasmine]
          filters: *all_tags
      - release-image:
          name: release-majora-base
          image: majora-base
          filters: *all_tags
      - release-image:
          name: release-majora-base-arm64
          image: majora-base
          arch: arm64
          filters: *all_tags
      - release-image:
          name: release-circleci_majora-base
          image: circleci_majora-base
          filters: *all_tags
      - release-image:
          name: release-circleci_majora-base-arm64
          image: circleci_majora-base
          arch: arm64
          filters: *all_tags
      - release-image:
          name: release-production_majora-base
          image: production_majora-base
          filters: *all_tags
      - release-image:
          name: release-production_majora-base-arm64
          image: production_majora-base
          arch: arm64
          filters: *all_tags
      - release-image:
          name: release-vite_majora-base
          image: vite_majora-base
          filters: *all_tags
      - release-image:
          name: release-vite_majora-base-arm64
          image: vite_majora-base
          arch: arm64
          filters: *all_tags
      - build-and-release:
          requires: [pytest, jasmine, frontend-checks, checks, release-production_majora-base, release-production_majora-base-arm64]
          filters: &tags_only
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
      - upload_proxy_files:
          requires: [pytest, jasmine, frontend-checks, checks]
          filters: *tags_only
      - upload_fe_files:
          requires: [pytest, jasmine, frontend-checks, checks, release-vite_majora-base, release-vite_majora-base-arm64]
          filters: *tags_only
      - link_photos:
          requires: [pytest, jasmine, frontend-checks, checks]
          filters: *tags_only
      - upload_admin_assets:
          requires: [pytest, jasmine, frontend-checks, checks, release-circleci_majora-base]
          filters: *tags_only
      - release:
          requires:
            - build-and-release
            - upload_proxy_files
            - upload_fe_files
            - link_photos
            - upload_admin_assets
            - release-majora-base
            - release-majora-base-arm64
            - release-circleci_majora-base
            - release-circleci_majora-base-arm64
            - release-production_majora-base
            - release-production_majora-base-arm64
            - release-vite_majora-base
            - release-vite_majora-base-arm64
          filters: *tags_only
      - warm-up-cache:
          requires: [release]
          filters: *tags_only
jobs:
  release-image:
    parameters:
      image:
        type: string
      arch:
        type: string
        default: ""
    machine: true
    steps:
      - checkout
      - run:
          name: Set up QEMU
          command: bin/image.sh qemu << parameters.image >>
      - run:
          name: Release
          command: bin/image.sh push << parameters.image >> << parameters.arch >>

  pytest:
    docker:
      - image: darthjee/circleci_majora-base:0.1.0
        environment:
          MAJORA_MYSQL_HOST: mysql
          MAJORA_MYSQL_PORT: 3306
          MAJORA_MYSQL_USER: root
          MAJORA_MYSQL_NAME: majora
          MAJORA_MYSQL_PASSWORD: majora
      - image: cimg/mysql:8.0
        name: mysql
        environment:
          MYSQL_DATABASE: majora
          MYSQL_USER: majora
          MYSQL_PASSWORD: majora
          MYSQL_ROOT_PASSWORD: majora
    steps:
      - checkout
      - run:
          name: Set folder
          command: rm frontend -rf; cp source/* ./ -r; rm source -rf
      - run:
          name: Poetry Install
          command: poetry install --no-root --no-interaction --no-ansi
      - run:
          name: migrate
          command: bin/configure_database.sh all
      - run:
          name: Tests
          command: poetry run pytest --cov --cov-report=lcov:coverage/lcov.info
      - run:
          name: Upload coverage to Codacy (partial)
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r coverage/lcov.info

  jasmine:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - checkout
      - run:
          name: Set folder
          command: rm source -rf; cp frontend/* ./ -r; rm frontend -rf
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Tests
          command: npm run coverage
      - run:
          name: Upload coverage to Codacy (partial)
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r coverage/lcov.info

  coverage-final:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - run:
          name: Finalize coverage on Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) final

  checks:
    docker:
      - image: darthjee/circleci_majora-base:0.1.0
    steps:
      - checkout
      - run:
          name: Set folder
          command: rm frontend -rf; cp source/* ./ -r; rm source -rf
      - run:
          name: Poetry Install
          command: poetry install --no-root --no-interaction --no-ansi
      - run:
          name: Check python Lint
          command: poetry run ruff check .
      - run:
          name: Check Python complexity
          command: bin/reports.sh ci

  frontend-checks:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - checkout
      - run:
          name: Set folder
          command: rm source -rf; cp frontend/* ./ -r; rm frontend -rf
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Check JS Lint
          command: npm run lint

  upload_proxy_files:
    docker:
      - image: darthjee/tent:0.7.8
    working_directory: /home/app/app
    steps:
      - checkout
      - run:
          name: Generate key file
          command: bin/deploy_frontend.sh generate_key_file
      - run:
          name: Upload proxy files
          command: SOURCE=/var/www/html/ bin/deploy_frontend.sh upload
      - run:
          name: Upload proxy configuration
          command: SOURCE=prod_proxy_config/ SSH_REMOTE_TEMP_DIR=$SSH_REMOTE_TEMP_DIR/configuration/ bin/deploy_frontend.sh upload
      - run:
          name: Setup hosts
          command: TARGET=configuration/hosts.php SSH_REMOTE_TEMP_DIR=$SSH_REMOTE_TEMP_DIR/configuration/ bin/deploy_frontend.sh copy_files

  upload_fe_files:
    docker:
      - image: darthjee/vite_majora-base:0.1.0
    steps:
      - checkout
      - run:
          name: Set folder
          command: rm source -rf; cp frontend/* ./ -r; rm frontend -rf
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Build assets
          command: bin/deploy_frontend.sh build
      - run:
          name: Generate key file
          command: bin/deploy_frontend.sh generate_key_file
      - run:
          name: Generate folder
          command: SSH_REMOTE_TEMP_DIR=$SSH_REMOTE_TEMP_DIR/static/ bin/deploy_frontend.sh generate_folder
      - run:
          name: Upload assets
          command: SOURCE=dist/ SSH_REMOTE_TEMP_DIR=$SSH_REMOTE_TEMP_DIR/static/ bin/deploy_frontend.sh upload

  link_photos:
    docker:
      - image: darthjee/tent:0.7.8
    working_directory: /home/app/app
    steps:
      - checkout
      - run:
          name: Generate key file
          command: bin/deploy_frontend.sh generate_key_file
      - run:
          name: Generate folder
          command: bin/deploy_frontend.sh generate_folder
      - run:
          name: Link photos
          command: SOURCE=$REMOTE_HOME/photos TARGET=$SSH_REMOTE_TEMP_DIR/photos bin/deploy_frontend.sh link

  upload_admin_assets:
    docker:
      - image: darthjee/circleci_majora-base:0.1.0
    steps:
      - checkout
      - run:
          name: Set folder
          command: rm frontend -rf; cp source/* ./ -r; rm source -rf
      - run:
          name: Poetry Install
          command: poetry install --no-root --no-interaction --no-ansi
      - run:
          name: Collect static files
          command: poetry run python manage.py collectstatic --noinput
      - run:
          name: Generate key file
          command: bin/deploy_frontend.sh generate_key_file
      - run:
          name: Generate folder
          command: SSH_REMOTE_TEMP_DIR=$SSH_REMOTE_TEMP_DIR/static/assets/admin/ bin/deploy_frontend.sh generate_folder
      - run:
          name: Upload admin assets
          command: SOURCE=staticfiles/admin/ SSH_REMOTE_TEMP_DIR=$SSH_REMOTE_TEMP_DIR/static/assets/admin/ bin/deploy_frontend.sh upload

  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Trigger Deploy
          command: scripts/deploy.sh deploy

  release:
    docker:
      - image: darthjee/vite_majora-base:0.1.0
    steps:
      - checkout
      - run:
          name: Generate key file
          command: bin/deploy_frontend.sh generate_key_file
      - run:
          name: Release assets
          command: bin/deploy_frontend.sh release

  warm-up-cache:
    docker:
      - image: darthjee/navi-hey:latest
    steps:
      - checkout
      - run:
          name: Warm up proxy cache
          command: navi-hey --config .circleci/navi_config.yaml
