web:
  port: $NAVI_PORT
workers:
  quantity: 5
  retry_cooldown: 10000
  sleep: 500
  max-retries: 50

failure:
  threshold: 0.0

clients:
  default:
    base_url: $MAJORA_PRODUCTION_URL
    timeout: 20000

resources:
  treasures:
    - url: /treasures.json
      status: 200
      paginated_actions:
        - resource: paginated_treasures
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_treasures:
    - url: /treasures.json?page={:page}
      status: 200
      actions:
        - resource: treasure_detail
          parameters:
            id: parsedBody.id

  treasure_detail:
    - url: /treasures/{:id}.json
      status: 200

  games:
    - url: /games.json
      status: 200
      paginated_actions:
        - resource: paginated_games
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_games:
    - url: /games.json?page={:page}
      status: 200
      actions:
        - resource: game_detail
          parameters:
            slug: parsedBody.game_slug
        - resource: game_pcs
          parameters:
            slug: parsedBody.game_slug
        - resource: game_npcs
          parameters:
            slug: parsedBody.game_slug
        - resource: game_treasures
          parameters:
            slug: parsedBody.game_slug
        - resource: game_items
          parameters:
            slug: parsedBody.game_slug
        - resource: game_documents
          parameters:
            slug: parsedBody.game_slug
        - resource: game_sessions
          parameters:
            slug: parsedBody.game_slug

  game_detail:
    - url: /games/{:slug}.json
      status: 200
      actions:
        - resource: short_game_pcs
          parameters:
            slug: parsedBody.game_slug
        - resource: short_game_npcs
          parameters:
            slug: parsedBody.game_slug

  short_game_pcs:
    - url: /games/{:slug}/pcs.json?per_page=5
      status: 200

  short_game_npcs:
    - url: /games/{:slug}/npcs.json?per_page=5
      status: 200

  game_pcs:
    - url: /games/{:slug}/pcs.json
      status: 200
      paginated_actions:
        - resource: paginated_game_pcs
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_pcs:
    - url: /games/{:slug}/pcs.json?page={:page}
      status: 200
      actions:
        - resource: pc
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  game_npcs:
    - url: /games/{:slug}/npcs.json
      status: 200
      paginated_actions:
        - resource: paginated_game_npcs
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_npcs:
    - url: /games/{:slug}/npcs.json?page={:page}
      status: 200
      actions:
        - resource: npc
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  game_treasures:
    - url: /games/{:slug}/treasures.json
      status: 200
      paginated_actions:
        - resource: paginated_game_treasures
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_treasures:
    - url: /games/{:slug}/treasures.json?page={:page}
      status: 200

  game_items:
    - url: /games/{:slug}/items.json
      status: 200
      paginated_actions:
        - resource: paginated_game_items
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_items:
    - url: /games/{:slug}/items.json?page={:page}
      status: 200
      actions:
        - resource: game_item_detail
          parameters:
            slug: parameters.slug
            id: parsedBody.id

  game_item_detail:
    - url: /games/{:slug}/items/{:id}.json
      status: 200

  game_documents:
    - url: /games/{:slug}/documents.json
      status: 200
      paginated_actions:
        - resource: paginated_game_documents
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_documents:
    - url: /games/{:slug}/documents.json?page={:page}
      status: 200

  game_sessions:
    - url: /games/{:slug}/sessions/past.json
      status: 200
      paginated_actions:
        - resource: paginated_game_sessions_past
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false
    - url: /games/{:slug}/sessions/future.json
      status: 200
      paginated_actions:
        - resource: paginated_game_sessions_future
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false
    - url: /games/{:slug}/sessions/unscheduled.json
      status: 200
      paginated_actions:
        - resource: paginated_game_sessions_unscheduled
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_sessions_past:
    - url: /games/{:slug}/sessions/past.json?page={:page}
      status: 200
      actions:
        - resource: session
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  paginated_game_sessions_future:
    - url: /games/{:slug}/sessions/future.json?page={:page}
      status: 200
      actions:
        - resource: session
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  paginated_game_sessions_unscheduled:
    - url: /games/{:slug}/sessions/unscheduled.json?page={:page}
      status: 200
      actions:
        - resource: session
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  session:
    - url: /games/{:slug}/sessions/{:id}.json
      status: 200

  pc:
    - url: /games/{:slug}/pcs/{:id}.json
      status: 200
      actions:
        - resource: pc_photos
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_pc_photos
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: pc_treasures
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_pc_treasures
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: pc_items
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_pc_items
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: pc_documents
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_pc_documents
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id

  pc_photos:
    - url: /games/{:slug}/pcs/{:id}/photos.json
      status: 200
      paginated_actions:
        - resource: paginated_pc_photos
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_pc_photos:
    - url: /games/{:slug}/pcs/{:id}/photos.json?page={:page}
      status: 200

  short_pc_photos:
    - url: /games/{:slug}/pcs/{:id}/photos.json?per_page=11
      status: 200

  pc_treasures:
    - url: /games/{:slug}/pcs/{:id}/treasures.json
      status: 200
      paginated_actions:
        - resource: paginated_pc_treasures
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_pc_treasures:
    - url: /games/{:slug}/pcs/{:id}/treasures.json?page={:page}
      status: 200

  short_pc_treasures:
    - url: /games/{:slug}/pcs/{:id}/treasures.json?per_page=5
      status: 200

  pc_items:
    - url: /games/{:slug}/pcs/{:id}/items.json
      status: 200
      paginated_actions:
        - resource: paginated_pc_items
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_pc_items:
    - url: /games/{:slug}/pcs/{:id}/items.json?page={:page}
      status: 200
      actions:
        - resource: pc_item_detail
          parameters:
            slug: parameters.slug
            id: parameters.id
            item_id: parsedBody.id

  pc_item_detail:
    - url: /games/{:slug}/pcs/{:id}/items/{:item_id}.json
      status: 200

  short_pc_items:
    - url: /games/{:slug}/pcs/{:id}/items.json?per_page=5
      status: 200

  pc_documents:
    - url: /games/{:slug}/pcs/{:id}/documents.json
      status: 200
      paginated_actions:
        - resource: paginated_pc_documents
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_pc_documents:
    - url: /games/{:slug}/pcs/{:id}/documents.json?page={:page}
      status: 200

  short_pc_documents:
    - url: /games/{:slug}/pcs/{:id}/documents.json?per_page=5
      status: 200

  npc:
    - url: /games/{:slug}/npcs/{:id}.json
      status: 200
      actions:
        - resource: npc_photos
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_npc_photos
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: npc_treasures
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_npc_treasures
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: npc_items
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_npc_items
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: npc_documents
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id
        - resource: short_npc_documents
          parameters:
            slug: parsedBody.game_slug
            id: parsedBody.id

  npc_photos:
    - url: /games/{:slug}/npcs/{:id}/photos.json
      status: 200
      paginated_actions:
        - resource: paginated_npc_photos
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_npc_photos:
    - url: /games/{:slug}/npcs/{:id}/photos.json?page={:page}
      status: 200

  short_npc_photos:
    - url: /games/{:slug}/npcs/{:id}/photos.json?per_page=11
      status: 200

  npc_treasures:
    - url: /games/{:slug}/npcs/{:id}/treasures.json
      status: 200
      paginated_actions:
        - resource: paginated_npc_treasures
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_npc_treasures:
    - url: /games/{:slug}/npcs/{:id}/treasures.json?page={:page}
      status: 200

  short_npc_treasures:
    - url: /games/{:slug}/npcs/{:id}/treasures.json?per_page=5
      status: 200

  npc_items:
    - url: /games/{:slug}/npcs/{:id}/items.json
      status: 200
      paginated_actions:
        - resource: paginated_npc_items
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_npc_items:
    - url: /games/{:slug}/npcs/{:id}/items.json?page={:page}
      status: 200
      actions:
        - resource: npc_item_detail
          parameters:
            slug: parameters.slug
            id: parameters.id
            item_id: parsedBody.id

  npc_item_detail:
    - url: /games/{:slug}/npcs/{:id}/items/{:item_id}.json
      status: 200

  short_npc_items:
    - url: /games/{:slug}/npcs/{:id}/items.json?per_page=5
      status: 200

  npc_documents:
    - url: /games/{:slug}/npcs/{:id}/documents.json
      status: 200
      paginated_actions:
        - resource: paginated_npc_documents
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_npc_documents:
    - url: /games/{:slug}/npcs/{:id}/documents.json?page={:page}
      status: 200

  short_npc_documents:
    - url: /games/{:slug}/npcs/{:id}/documents.json?per_page=5
      status: 200
