web:
  port: $NAVI_PORT
workers:
  quantity: 5
  retry_cooldown: 10000
  sleep: 500
  max-retries: 50

failure:
  threshold: 0.0

clients:
  default:
    base_url: $MAJORA_PRODUCTION_URL
    timeout: 20000

resources:
  treasures:
    - url: /treasures.json
      status: 200
      paginated_actions:
        - resource: paginated_treasures
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_treasures:
    - url: /treasures.json?page={:page}
      status: 200
      actions:
        - resource: treasure_detail
          parameters:
            id: parsedBody.id

  treasure_detail:
    - url: /treasures/{:id}.json
      status: 200

  games:
    - url: /games.json
      status: 200
      paginated_actions:
        - resource: paginated_games
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_games:
    - url: /games.json?page={:page}
      status: 200
      actions:
        - resource: game_detail
          parameters:
            slug: parsedBody.game_slug
        - resource: game_pcs
          parameters:
            slug: parsedBody.game_slug
        - resource: game_npcs
          parameters:
            slug: parsedBody.game_slug
        - resource: game_treasures
          parameters:
            slug: parsedBody.game_slug

  game_detail:
    - url: /games/{:slug}.json
      status: 200
      actions:
        - resource: short_game_pcs
          parameters:
            slug: parsedBody.game_slug
        - resource: short_game_npcs
          parameters:
            slug: parsedBody.game_slug

  short_game_pcs:
    - url: /games/{:slug}/pcs.json?per_page=6
      status: 200

  short_game_npcs:
    - url: /games/{:slug}/npcs.json?per_page=6
      status: 200

  game_pcs:
    - url: /games/{:slug}/pcs.json
      status: 200
      paginated_actions:
        - resource: paginated_game_pcs
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_pcs:
    - url: /games/{:slug}/pcs.json?page={:page}
      status: 200
      actions:
        - resource: pc
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  game_npcs:
    - url: /games/{:slug}/npcs.json
      status: 200
      paginated_actions:
        - resource: paginated_game_npcs
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_npcs:
    - url: /games/{:slug}/npcs.json?page={:page}
      status: 200
      actions:
        - resource: npc
          parameters:
            id: parsedBody.id
            slug: parsedBody.game_slug

  game_treasures:
    - url: /games/{:slug}/treasures.json
      status: 200
      paginated_actions:
        - resource: paginated_game_treasures
          pagination:
            - pages: headers['pages']
            - page_key: page
            - zero_indexed: false

  paginated_game_treasures:
    - url: /games/{:slug}/treasures.json?page={:page}
      status: 200

  pc:
    - url: /games/{:slug}/pcs/{:id}.json
      status: 200

  npc:
    - url: /games/{:slug}/npcs/{:id}.json
      status: 200
