web:
  port: $NAVI_PORT
workers:
  quantity: 5
  retry_cooldown: 10000
  sleep: 500
  max-retries: 50

failure:
  threshold: 0.0

include:
  - resources/treasures.yml
  - resources/domains.yml
  - resources/games.yml
  - resources/pcs.yml
  - resources/npcs.yml
  - resources/items.yml
  - resources/factions.yml
  - resources/possessions.yml
  - resources/common_items.yml
  - resources/documents.yml
  - resources/sessions.yml
  - resources/permissions.yml
  - resources/clients.yml
