"""Views package for the games app."""

from .access_route_config import access_route_config
from .auth import account, language, login, logout, register, status, test_email
from .game import (
    game_npc_access,
    game_npc_detail,
    game_npc_full,
    game_npc_permissions,
    game_npc_photo_set,
    game_npc_photo_upload,
    game_npc_photos,
    game_npc_treasure_acquire,
    game_npc_treasure_sell,
    game_npc_treasures,
    game_npcs,
    game_npcs_all,
    game_pc_access,
    game_pc_detail,
    game_pc_full,
    game_pc_permissions,
    game_pc_photo_set,
    game_pc_photo_upload,
    game_pc_photos,
    game_pc_treasure_acquire,
    game_pc_treasure_sell,
    game_pc_treasures,
    game_pcs,
)
from .game_masters import game_master_detail, game_masters_list
from .game_sessions import (
    game_session_detail,
    game_sessions_create,
    game_sessions_future,
    game_sessions_past,
    game_sessions_unscheduled,
    session_messages_list,
)
from .game_tasks import game_task_detail, game_tasks_list
from .games import (
    game_access,
    game_detail,
    game_permissions,
    game_photos,
    game_treasure_detail,
    game_treasures,
    game_treasures_all,
    games_list,
)
from .health import health
from .password_reset import recover, reset_password
from .photo_upload import photo_upload
from .polls import game_poll_detail, game_polls_list
from .ready import ready
from .staff import staff_user_detail, staff_user_recovery_link, staff_users_list
from .treasures import (
    treasure_access,
    treasure_detail,
    treasure_permissions,
    treasure_photo_upload,
    treasures_list,
)
from .upload_finalize import upload_finalize

__all__ = [
    'games_list',
    'game_detail',
    'game_access',
    'game_permissions',
    'game_treasures',
    'game_treasures_all',
    'game_treasure_detail',
    'game_photos',
    'game_pcs',
    'game_npcs',
    'game_npcs_all',
    'game_npc_access',
    'game_npc_detail',
    'game_npc_full',
    'game_pc_access',
    'game_pc_detail',
    'game_pc_full',
    'game_pc_permissions',
    'game_npc_permissions',
    'game_pc_photo_upload',
    'game_npc_photo_upload',
    'game_pc_photo_set',
    'game_npc_photo_set',
    'game_pc_photos',
    'game_npc_photos',
    'game_pc_treasures',
    'game_npc_treasures',
    'game_pc_treasure_acquire',
    'game_pc_treasure_sell',
    'game_npc_treasure_acquire',
    'game_npc_treasure_sell',
    'game_masters_list',
    'game_master_detail',
    'game_sessions_create',
    'game_session_detail',
    'game_sessions_past',
    'game_sessions_future',
    'game_sessions_unscheduled',
    'session_messages_list',
    'game_tasks_list',
    'game_task_detail',
    'language',
    'login',
    'logout',
    'register',
    'status',
    'test_email',
    'account',
    'recover',
    'reset_password',
    'photo_upload',
    'game_polls_list',
    'game_poll_detail',
    'staff_users_list',
    'staff_user_detail',
    'staff_user_recovery_link',
    'treasure_access',
    'treasure_permissions',
    'treasure_detail',
    'treasure_photo_upload',
    'treasures_list',
    'upload_finalize',
    'health',
    'ready',
    'access_route_config',
]
