"""Versioning app admin configuration.

Registers each `Historical<Model>` generated by `django-simple-history` for the tracked
`games` models as a read-only entry in Django Admin, so change history can be inspected
without allowing edits to past snapshots.
"""

from django.contrib import admin

from games.models import (
    Character,
    CharacterLink,
    CharacterPhoto,
    CharacterTreasure,
    Game,
    GamePhoto,
    Link,
    Player,
    Treasure,
    TreasurePhoto,
)

HISTORICAL_MODELS = [
    Character.history.model,
    CharacterLink.history.model,
    CharacterPhoto.history.model,
    CharacterTreasure.history.model,
    Game.history.model,
    GamePhoto.history.model,
    Link.history.model,
    Player.history.model,
    Treasure.history.model,
    TreasurePhoto.history.model,
]


class ReadOnlyHistoricalRecordAdmin(admin.ModelAdmin):
    """Admin configuration exposing historical records for inspection only, never editing."""

    def has_add_permission(self, request):
        """Disallow creating historical records through the admin."""
        return False

    def has_change_permission(self, request, obj=None):
        """Disallow editing historical records through the admin."""
        return False

    def has_delete_permission(self, request, obj=None):
        """Disallow deleting historical records through the admin."""
        return False


for historical_model in HISTORICAL_MODELS:
    admin.site.register(historical_model, ReadOnlyHistoricalRecordAdmin)
