# Generated by Django 5.2.15 on 2026-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0002_historicalgame_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreasure',
            name='game_type',
            field=models.CharField(
                choices=[('dnd', 'D&D'), ('deadlands', 'Deadlands')],
                default='dnd',
                max_length=16,
            ),
        ),
    ]
