# Generated by Django 5.2.15 on 2026-07-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0004_historicalcharactertreasure_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltreasure',
            name='hidden',
        ),
    ]
