# Generated by Django 5.2.15 on 2026-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "versioning",
            "0008_historicalcharacterdocument_historicalcharacterdocumentphoto_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcharacterlink",
            name="link_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lootstudio", "LootStudio"),
                    ("diary", "Diary"),
                    ("music", "Music"),
                    ("stl", "STL"),
                    ("background", "Background"),
                    ("reference", "Reference"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicallink",
            name="link_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lootstudio", "LootStudio"),
                    ("diary", "Diary"),
                    ("music", "Music"),
                    ("stl", "STL"),
                    ("background", "Background"),
                    ("reference", "Reference"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
