# Generated by Django 5.2.15 on 2026-07-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0010_historicalauthorizationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='allegiance',
            new_name='private_allegiance',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='slain',
            new_name='private_slain',
        ),
    ]
