# Generated by Django 5.2.15 on 2026-07-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0015_historicalcharacter_incognito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcharacterdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalcharacterdocument',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalcharacterdocument',
            name='photo',
        ),
        migrations.DeleteModel(
            name='HistoricalCharacterDocumentPhoto',
        ),
    ]
