# Generated by Django 5.2.15 on 2026-07-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0016_remove_historicalcharacterdocument_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='profile_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='historicalgame',
            old_name='cover_photo',
            new_name='photo',
        ),
    ]
