# Generated by Django 5.2.15 on 2026-08-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0081_alter_characterlink_link_type_alter_gamelink_link_type"),
        ("versioning", "0017_rename_profile_photo_historicalcharacter_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcharacterlink",
            name="link_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lootstudio", "LootStudio"),
                    ("youtube", "YouTube"),
                    ("diary", "Diary"),
                    ("music", "Music"),
                    ("stl", "STL"),
                    ("background", "Background"),
                    ("reference", "Reference"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgamelink",
            name="link_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lootstudio", "LootStudio"),
                    ("youtube", "YouTube"),
                    ("diary", "Diary"),
                    ("music", "Music"),
                    ("stl", "STL"),
                    ("background", "Background"),
                    ("reference", "Reference"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
