# Generated by Django 5.2.15 on 2026-08-04 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0019_historicalgame_game_domain_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalgamedomain',
            name='schemes',
            field=models.CharField(
                default='https',
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message='schemes must be a comma-separated list made only of'
                        ' "http"/"https".',
                        regex='^(http|https)(,(http|https))*$',
                    )
                ],
            ),
        ),
    ]
