# Generated by Django 5.2.15 on 2026-08-04 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0020_historicalgamedomain_schemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalgamedomain',
            name='domain',
            field=models.CharField(
                db_index=True,
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message='domain must be a valid hostname (labels of letters, digits'
                        ' and hyphens separated by dots, no wildcards or whitespace).',
                        regex=(
                            '\\A([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)'
                            '(\\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+\\Z'
                        ),
                    )
                ],
            ),
        ),
    ]
