# Generated by Django 5.2.15 on 2026-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0021_alter_historicalgamedomain_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgame',
            name='game_domain_group',
        ),
        migrations.AddField(
            model_name='historicalgamedomain',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
