# Generated by Django 5.2.15 on 2026-08-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versioning", "0026_historicalcollection_historicalcollectionphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstlmodel",
            name="owned",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalstlmodel",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("human", "Human"),
                    ("elf", "Elf"),
                    ("dwarf", "Dwarf"),
                    ("halfling", "Halfling"),
                    ("gnome", "Gnome"),
                    ("half-elf", "Half-Elf"),
                    ("half-orc", "Half-Orc"),
                    ("tiefling", "Tiefling"),
                    ("dragonborn", "Dragonborn"),
                    ("orc", "Orc"),
                    ("goblin", "Goblin"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalstlmodel",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("barbarian", "Barbarian"),
                    ("bard", "Bard"),
                    ("cleric", "Cleric"),
                    ("druid", "Druid"),
                    ("fighter", "Fighter"),
                    ("monk", "Monk"),
                    ("paladin", "Paladin"),
                    ("ranger", "Ranger"),
                    ("rogue", "Rogue"),
                    ("sorcerer", "Sorcerer"),
                    ("warlock", "Warlock"),
                    ("wizard", "Wizard"),
                    ("archer", "Archer"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalstlmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("terrain", "Terrain"),
                    ("prop", "Prop"),
                    ("creature", "Creature"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
