# Generated by Django 5.2.15 on 2026-08-14 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versioning", "0030_historicalcharacterpossession"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstlmodel",
            name="url",
            field=models.URLField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AddField(
            model_name="historicalstlmodel",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tiny", "Tiny"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("huge", "Huge"),
                    ("gargantuan", "Gargantuan"),
                    ("life", "Life"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="historicalstlmodel",
            name="race",
        ),
        migrations.RemoveField(
            model_name="historicalstlmodel",
            name="role",
        ),
    ]
