# Generated by Django 5.2.15 on 2026-08-14 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versioning", "0032_rename_historicalfaction_historicalgamefaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcharacterlink",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])]
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollection",
            name="url",
            field=models.URLField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="historicalgamelink",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])]
            ),
        ),
        migrations.AlterField(
            model_name="historicalsource",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="historicalstlmodellink",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])]
            ),
        ),
    ]
