# Generated by Django 5.2.17 on 2026-08-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0035_historicaldomainconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldomain',
            name='title',
        ),
    ]
