# Generated by Django 5.2.17 on 2026-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0037_historicalpasswordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcollection',
            name='external_id',
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=200, null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalstlmodel',
            name='external_id',
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=200, null=True,
            ),
        ),
    ]
