# Generated by Django 5.2.17 on 2026-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerDebugEmission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
