# Generated by Django 5.2.15 on 2026-08-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miniatures", "0002_source_url_sourcephoto_source_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "url",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections",
                        to="miniatures.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stlmodel",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="stl_models", to="miniatures.collection"
            ),
        ),
        migrations.CreateModel(
            name="CollectionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("ready", models.BooleanField(default=False)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="miniatures.collection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="miniatures.collectionphoto",
            ),
        ),
    ]
