# Generated by Django 5.2.15 on 2026-08-14 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miniatures", "0004_stlmodel_owned_stlmodel_race_stlmodel_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stlmodel",
            name="url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                unique=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AddField(
            model_name="stlmodel",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tiny", "Tiny"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("huge", "Huge"),
                    ("gargantuan", "Gargantuan"),
                    ("life", "Life"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StlModelRace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creature",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("elf", "Elf"),
                            ("dwarf", "Dwarf"),
                            ("halfling", "Halfling"),
                            ("gnome", "Gnome"),
                            ("half-elf", "Half-Elf"),
                            ("half-orc", "Half-Orc"),
                            ("tiefling", "Tiefling"),
                            ("dragonborn", "Dragonborn"),
                            ("orc", "Orc"),
                            ("goblin", "Goblin"),
                            ("turtlefolk", "Turtlefolk"),
                            ("cthulhufolk", "Cthulhufolk"),
                            ("humanoid", "Humanoid"),
                            ("construct", "Construct"),
                            ("monstrosity", "Monstrosity"),
                            ("undead", "Undead"),
                            ("aberration", "Aberration"),
                            ("beast", "Beast"),
                            ("alien", "Alien"),
                            ("fiend", "Fiend"),
                            ("fey", "Fey"),
                            ("giant", "Giant"),
                            ("dragon", "Dragon"),
                            ("celestial", "Celestial"),
                            ("elemental", "Elemental"),
                            ("cyborg", "Cyborg"),
                            ("plant", "Plant"),
                            ("ooze", "Ooze"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "stl_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="races",
                        to="miniatures.stlmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("stl_model", "creature")},
            },
        ),
        migrations.CreateModel(
            name="StlModelRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("barbarian", "Barbarian"),
                            ("bard", "Bard"),
                            ("cleric", "Cleric"),
                            ("druid", "Druid"),
                            ("fighter", "Fighter"),
                            ("monk", "Monk"),
                            ("paladin", "Paladin"),
                            ("ranger", "Ranger"),
                            ("rogue", "Rogue"),
                            ("sorcerer", "Sorcerer"),
                            ("warlock", "Warlock"),
                            ("wizard", "Wizard"),
                            ("archer", "Archer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "stl_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles",
                        to="miniatures.stlmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("stl_model", "role")},
            },
        ),
    ]
