# Generated by Django 5.2.15 on 2026-08-14 01:58

from django.db import migrations


def copy_race_role_to_join_tables(apps, schema_editor):
    """Copy every non-null `StlModel.race`/`role` scalar value into the new join tables."""
    StlModel = apps.get_model("miniatures", "StlModel")
    StlModelRace = apps.get_model("miniatures", "StlModelRace")
    StlModelRole = apps.get_model("miniatures", "StlModelRole")

    for stl_model in StlModel.objects.all():
        if stl_model.race:
            StlModelRace.objects.create(stl_model=stl_model, creature=stl_model.race)
        if stl_model.role:
            StlModelRole.objects.create(stl_model=stl_model, role=stl_model.role)


def noop_reverse(apps, schema_editor):
    """No-op reverse -- the dropped `race`/`role` columns are not recreated by `migrate` back."""


class Migration(migrations.Migration):
    dependencies = [
        ("miniatures", "0005_stlmodel_url_stlmodel_size_stlmodelrace_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_race_role_to_join_tables, noop_reverse),
        migrations.RemoveField(
            model_name="stlmodel",
            name="race",
        ),
        migrations.RemoveField(
            model_name="stlmodel",
            name="role",
        ),
    ]
