# Generated by Django 5.2.15 on 2026-08-14 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miniatures", "0006_copy_race_role_data_remove_stlmodel_race_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="url",
            field=models.URLField(
                blank=True,
                default=None,
                null=True,
                unique=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="stlmodellink",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])]
            ),
        ),
    ]
