# Generated by Django 5.2.17 on 2026-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0007_alter_collection_url_alter_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='external_id',
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True, unique=True,
            ),
        ),
        migrations.AddField(
            model_name='stlmodel',
            name='external_id',
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True, unique=True,
            ),
        ),
    ]
