# GamePermissionsSerializer's can_* fields.
edit: []
regular_edit:
  - staff
  - player
create_item:
  - staff
  - player
create_document:
  - staff
  - player
create_possession:
  - staff
  - player
edit_session:
  - staff
  - player
create_npc:
  - staff
  - player
